---
#TODO
#yarn 53端口冲突
#https://archive.cloudera.com/p/HDP 域名屏蔽
- name: 添加hdp apt认证文件
  copy:
    src: trusted.gpg
    dest: /etc/apt/trusted.gpg

- name: 安装apache2文件服务
  shell:
    cmd: apt-get install -y apache2

- name: 删除文件服务默认页面
  shell:
    cmd: rm -fr /var/www/html/index.html

- name: 拷贝hdp镜像源资源到其他节点（大文件压缩拷贝，比unarchive效率高）
  copy:
    src: "{{ item }}"
    dest: /var/www/html/
  with_items:
    - ambari-2.7.5.0-ubuntu18.tar.gz
    - HDP-UTILS-1.1.0.22-ubuntu18.tar.gz
    - HDP-GPL-3.1.5.0-ubuntu18-gpl.tar.gz
    - HDP-3.1.5.0-ubuntu18-deb.tar.gz

- name: 配置 ambari hdp镜像源
  shell:
    cmd: "{{ item }}"
  with_items:
    - tar -zxvf /var/www/html/ambari-2.7.5.0-ubuntu18.tar.gz -C /var/www/html/
    - tar -zxvf /var/www/html/HDP-3.1.5.0-ubuntu18-deb.tar.gz -C /var/www/html/
    - tar -zxvf /var/www/html/HDP-UTILS-1.1.0.22-ubuntu18.tar.gz -C /var/www/html/
    - tar -zxvf /var/www/html/HDP-GPL-3.1.5.0-ubuntu18-gpl.tar.gz -C /var/www/html/

- name: 解压ambari安装包
  unarchive:
    src: bigdata.debs.tar.gz
    dest: /opt/debs/

- name: 配置环境变量
  lineinfile:
    dest: /etc/apt/sources.list.d/local.list
    state: present
    line: "{{ item }}"
  with_items:
    - "deb [trusted=yes] file:/opt/debs bigdata/"
    - "deb [trusted=yes] http://{{ KEEPALIVED_VIP }}/ambari/ubuntu18/2.7.5.0-72/ Ambari main"

- name: 安装ambari
  shell:
    cmd: apt-get update && apt-get install -y ambari-server ambari-agent

- name: 删除，修改ambari metainfo.xml文件，禁用SMARTSENSE组件
  lineinfile:
    dest:  /var/lib/ambari-server/resources/stacks/HDP/3.0/services/SMARTSENSE/metainfo.xml
    state: absent
    regexp: '.*<selection>MANDATORY</selection>.*'

- name: 拷贝mysql-connector-java-8.0.30.jar
  copy:
    src: mysql-connector-java-8.0.30.jar
    dest: /usr/share/java/

- name: 创建ambari数据库
  command:  mysql --login-path=local -e "{{ item }}"
  with_items:
    - CREATE DATABASE ambari;
  when:
    - STATE == "MASTER"

- name: 初始化ambari数据库
  # 如果使用mysql mgr模式，注意每张表必须都有主键
  command:  mysql --login-path=local --database=ambari -e "{{ item }}"
  with_items:
    - source /opt/ansible-role-ambari/bigdata/roles/ambari/files/Ambari-DDL-MySQL-CREATE.sql;
  when:
    - STATE == "MASTER"

- name: 添加ambari password.dat文件
  template: src=password.dat.j2 dest=/etc/ambari-server/conf/password.dat owner=root

- name: 添加ambari ambari.properties文件
  template: src=ambari.properties.j2 dest=/etc/ambari-server/conf/ambari.properties owner=root

- name: 配置chk_mysql_master.sh #使用keepalived检测启停ambari-server
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 644

- name: 配置start_server.sh #配置重启ambari-server脚本
  copy:
    src: start_server.sh
    dest: /etc/keepalived/start_server.sh
    mode: 744

- name: 配置stop_server.sh #配置停止ambari-server脚本
  copy:
    src: stop_server.sh
    dest: /etc/keepalived/stop_server.sh
    mode: 744

- name: 启动keepalived服务
  sudo: yes
  service:
    name: keepalived
    state: restarted
    enabled: true