---
#TODO
#yarn 53端口冲突
- name: 解压ambari-agent安装包
  unarchive:
    src: bigdata.debs.tar.gz
    dest: /opt/debs/

- name: 配置环境变量
  lineinfile:
    dest: /etc/apt/sources.list.d/local.list
    state: present
    line: "{{ item }}"
  with_items:
    - "deb [trusted=yes] file:/opt/debs bigdata/"
    - "deb [trusted=yes] http://{{ KEEPALIVED_VIP }}/ambari/ubuntu18/2.7.5.0-72/ Ambari main"

- name: 安装ambari-agent
  shell:
    cmd: apt-get update && apt-get install -y ambari-agent